### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by csEylLee** [Lycus99/MT-FiST#1]
Hi, which paper does this source code correspond to? It looks like that it is about the surgical triplet recognition task, which I'm interested in.

**Comment by Lycus99** [comment]
Sorry, the paper is under review. If the paper is accepted, I will write a detailed code description. Thanks for your attention.

**Comment by csEylLee** [comment]
> Sorry, the paper is under review. If the paper is accepted, I will write a detailed code description. Thanks for your attention.

Good luck!
