### ISSUE TITLE
数据集划分

### ISSUE THREAD

**Issue by cascat0** [Lycus99/MT-FiST#2]
https://github.com/Lycus99/MT-FiST/blob/75b8676cab61fe8618960c521e6a3eb6867d894b/test.py#L582
您好。看起来您也是在cholect45或cholect50数据集上做surgical triplet的，我想问一下您的数据集划分方式是自己定义的吗？我看这行注释的val index不在官方的划分方式中。我最近也想自己定义划分数据集的方式，因为在官方的数据集划分上实在是跑不过他们论文里的结果哈哈哈。还望您解答。

**Comment by cascat0** [comment]
https://github.com/CAMMA-public/cholect50/blob/5080046bd4f0255b898c0c2da32c51b3fbcab721/dataloader_pth.py#L110

**Comment by Lycus99** [comment]
你好。我们的论文中主要有两个结果，一个是和SOTA对比，我们参加了CholecT2021的竞赛，使用的是官方的CholecTriplet2021数据集划分，汇报的也是竞赛结果。另一个是消融实验，因为当时还没有公开完整的CholecT50数据集，所以我们就自己划分的训练集和验证集，主要为了说明模块的有效性。我认为和SOTA对比还是要按照官方的数据集划分。

**Comment by cascat0** [comment]
> 你好。我们的论文中主要有两个结果，一个是和SOTA对比，我们参加了CholecT2021的竞赛，使用的是官方的CholecTriplet2021数据集划分，汇报的也是竞赛结果。另一个是消融实验，因为当时还没有公开完整的CholecT50数据集，所以我们就自己划分的训练集和验证集，主要为了说明模块的有效性。我认为和SOTA对比还是要按照官方的数据集划分。

感谢解答！刚看到你们的论文出版了，正在读。请问什么时候会开放全部代码呢？

**Comment by Lycus99** [comment]
已经更新了模型代码和权重

**Comment by 309020726** [comment]
How to generate the .pkl file required for training or testing? What format should it be stored in? What content does it contain?
