### ISSUE TITLE
Two question

### ISSUE THREAD

**Issue by csEylLee** [Lycus99/MT-FiST#4]
Q1: 'from models import model_provider' can be found.
Q2:Is 'model_all4' the model in your paper?

**Comment by csEylLee** [comment]
And can you share your .pkl file ?

**Comment by Lycus99** [comment]
A1: models/__init__.py
A2: 'model_lstm' is our final model. 
A3: .pkl file is larger than 25M. If you need it, I will send it by e-mail to you.

**Comment by dyy211hh** [comment]
And can you share your .pkl file ?

**Comment by Lycus99** [comment]
.pkl file has been uploaded: https://drive.google.com/drive/folders/1Wjo1AgDiSPjeysMDdhq5glpQ8qENFLDT.
This .pkl file was used for ablation studies, not for comparison with other SOTA methods. The results of the comparison were logged in the CholecTriplet2021 Challenge. @csEylLee @dyy211hh

**Comment by Lycus99** [comment]
`import pickle
with open('address_to_pickle.pkl', 'rb') as f:
    list = pickle.load(f)`

list[0]: training images address
list[1]: validation images
list[2]: train labels: I(6)+V(10)+T(15)+IVT(100)
list[3]: validation labels
list[4]: the number of each training video images
list[5]: the number of each validation video images

**Comment by dyy211hh** [comment]
Thank you for your answer.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/04/2024 09:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Lycus99/MT-FiST] Two question (Issue #4) |

import pickle with open('address_to_pickle.pkl', 'rb') as f: list = pickle.load(f)

list[0]: training images address
list[1]: validation images
list[2]: train labels: I(6)+V(10)+T(15)+IVT(100)
list[3]: validation labels
list[4]: the number of each training video images
list[5]: the number of each validation video images
